diccionario1 = {'a': 1, 2: 10}
diccionario2 = {10: 1, 2: 10}
diccionario3 = {True: True, False: False}
diccionario4 = { (12, 3): True }

# Podemos convertir un metodo instancia a un metodo clase con 

lista = [1, 2, 3, 4, 5]

sublista = lista[-3:]

print(sublista) # [3, 4, 5]

# Así podemos definir correctamente una función

def mi_funcion():
    pass

# Y así podemos definir una clase

class MiClase:
    pass

# Podemos ordenar una lista con el método sort}

def sumapares(numero_1=10, numero_2=20):
    return numero_1 + numero_2      

def SumaPares(numero_1=10, numero_2=20):
    return numero_1 + numero_2    

def suma_pares(numero_1=10, numero_2=20):
    return numero_1 + numero_2

def suma_pares(numero_1 = 10, numero_2 = 20):
    return numero_1 + numero_2